# Site settings
author: Christian Pardo
title: Brocoding
header-img: img/home-bg.png
email: chrispardopersonal@gmail.com
copyright_name: Christian Pardo
description: > # this means to ignore newlines until "baseurl:"
  The fun world of coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Bromaster369

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
